[package]
name = "madara_template"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# Simplified dependencies - no unstable features
base64 = { version = "0.22", default-features = false, features = ["alloc"] }