[package]
name = "poseidonscans"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
aidoku-stable-wrapper = { path = "../../templates/aidoku-stable-wrapper" }
